import { ALL_TILE_STRS } from '@contracts/tiles';
import type { TileStr } from '@contracts/tiles';

/**
 * The two face sets, and where each one comes from.
 *
 * **`traditional` is licensed art, fetched as a sprite sheet.** CC0 tiles from
 * [fluffystuff/riichi-mahjong-tiles](https://github.com/fluffystuff/riichi-mahjong-tiles), vendored
 * under `vendor/` with their licence and assembled into `public/tiles/traditional.svg` by
 * `npm run build:tiles`. It is a *fetched* set rather than an inlined one because the assembled
 * sheet is 284 kB raw — 22 kB over the wire, and cached independently of the app bundle, which is
 * the right trade for art that never changes while the app does. This is exactly the
 * *"one SVG sprite sheet per face set … a single request"* of `docs/08-graphics-ux.md` §3.
 *
 * **Upstream's faces are the design alone, on a transparent ground** — the slab it sits on is a
 * separate file (`Front.svg`), which is why this set keeps §3's *"tile body is CSS, not part of the
 * SVG"* exactly as written. Its `Back.svg` is the exception: that one *is* a complete tile, so the
 * CSS back steps aside for it. Hence {@link TileSetInfo.drawsBody} is per symbol rather than per
 * set — asserting it of a whole set is what put 136 painted designs on the felt with no tiles
 * under them.
 *
 * **`high-contrast` is geometry, in this file, inlined.** A large numeral and a suit letter, for
 * pond-size readability and low vision (§3). It stays inline and first-party for two reasons: it is
 * a few kB, and it is what the fetched set falls back *to* — so it must not itself depend on a
 * fetch succeeding.
 *
 * **Why the geometry uses no CJK fonts.** Nothing here needs one, now that the kanji come from real
 * art; the Latin digits and letters below are safe because every platform has those. The rule the
 * removed geometry was written under still stands for anything added here: a glyph that depends on
 * the machine's fonts renders as tofu on a headless CI image, and tofu passes a screenshot test.
 */

/** Face viewBox for the inline geometry. 100 × 136 is 44 × 60 stage units, to scale. */
export const FACE_VIEWBOX = '0 0 100 136';

/** The vendored art is drawn on a 300 × 400 tile. */
export const VENDOR_VIEWBOX = '0 0 300 400';

export type TileSet = 'traditional' | 'high-contrast';

export interface TileSetInfo {
  id: TileSet;
  label: string;
  /** Prefix of the `<symbol>` ids this set contributes to the document. */
  idPrefix: string;
  /**
   * Where the symbols come from. `inline` is generated by this module; `fetch` is a sprite sheet
   * served from `public/`, which the sprite service pulls in once.
   */
  source: { kind: 'inline' } | { kind: 'fetch'; url: string };
  /** The coordinate space this set's `<symbol>`s are drawn in. */
  viewBox: string;
  /**
   * Whether the art already includes the tile body — the slab, its edge, its shading — in which
   * case the component's own CSS body is suppressed and the symbol fills the whole element.
   *
   * Per symbol, because it genuinely differs within a set: the vendored faces are designs on a
   * transparent ground, while the vendored back is a finished tile.
   */
  drawsBody: { readonly face: boolean; readonly back: boolean };
  /** Symbol id for the face-down tile, when the set draws one. `null` falls back to the CSS back. */
  backSymbolId: string | null;
}

export const TILE_SET_INFO: Readonly<Record<TileSet, TileSetInfo>> = {
  traditional: {
    id: 'traditional',
    label: 'Traditional',
    idPrefix: 'mj-tr-',
    source: { kind: 'fetch', url: 'tiles/traditional.svg' },
    viewBox: VENDOR_VIEWBOX,
    // `Front.svg` — the bare slab — is not vendored, and is not wanted: the CSS body is that slab,
    // and it themes. `Back.svg` is a finished tile, so the CSS back gets out of its way.
    drawsBody: { face: false, back: true },
    backSymbolId: 'mj-tr-back',
  },
  'high-contrast': {
    id: 'high-contrast',
    label: 'High contrast',
    idPrefix: 'mj-hc-',
    source: { kind: 'inline' },
    viewBox: FACE_VIEWBOX,
    drawsBody: { face: false, back: false },
    backSymbolId: null,
  },
};

export const TILE_SETS: readonly TileSet[] = ['traditional', 'high-contrast'];

/** The set every other set falls back to: inline, always present, never a network request. */
export const FALLBACK_TILE_SET: TileSet = 'high-contrast';

const INK = 'currentColor';
const RED = 'var(--mj-face-red)';

// ---------------------------------------------------------------------------
// Primitives
// ---------------------------------------------------------------------------

/** Trim float noise out of the generated markup — the sprite test compares it byte-for-byte. */
function n(value: number): string {
  return String(Math.round(value * 100) / 100);
}

function bar(x: number, y: number, w: number, h: number, fill = INK, r = 2): string {
  return `<rect x="${n(x)}" y="${n(y)}" width="${n(w)}" height="${n(h)}" rx="${n(r)}" fill="${fill}"/>`;
}

// ---------------------------------------------------------------------------
// High-contrast set — a big numeral and a suit letter
// ---------------------------------------------------------------------------

const HC_SUIT_COLOUR: Readonly<Record<string, string>> = {
  m: 'var(--mj-hc-man)',
  p: 'var(--mj-hc-pin)',
  s: 'var(--mj-hc-sou)',
  z: 'var(--mj-hc-honor)',
};

/** Wind and dragon letters. Latin, because the point of this set is being readable at 26 px. */
const HC_HONOUR_LETTER: Readonly<Record<number, string>> = {
  1: 'E',
  2: 'S',
  3: 'W',
  4: 'N',
  5: 'H',
  6: 'G',
  7: 'R',
};

/** Kept distinct from the letter so a dragon is never read as a wind at pond size. */
const HC_HONOUR_KIND: Readonly<Record<number, string>> = {
  1: 'WIND',
  2: 'WIND',
  3: 'WIND',
  4: 'WIND',
  5: 'DRAGON',
  6: 'DRAGON',
  7: 'DRAGON',
};

const HC_DRAGON_COLOUR: Readonly<Record<number, string>> = {
  5: 'var(--mj-face-blue)',
  6: 'var(--mj-face-green)',
  7: RED,
};

function hcText(text: string, y: number, size: number, colour: string, weight = 800): string {
  return (
    `<text x="50" y="${n(y)}" text-anchor="middle" font-family="system-ui, -apple-system, ` +
    `'Segoe UI', Roboto, sans-serif" font-size="${n(size)}" font-weight="${String(weight)}" ` +
    `fill="${colour}">${text}</text>`
  );
}

function highContrastFace(tile: TileStr): string {
  const suit = tile[1] ?? 'z';
  const rank = Number(tile[0]);
  const red = rank === 0;
  const colour = red ? RED : (HC_SUIT_COLOUR[suit] ?? INK);

  if (suit === 'z') {
    const letter = HC_HONOUR_LETTER[rank] ?? '?';
    const letterColour = HC_DRAGON_COLOUR[rank] ?? colour;
    return (
      hcText(letter, 96, 88, letterColour) +
      hcText(HC_HONOUR_KIND[rank] ?? '', 122, 15, colour, 700)
    );
  }

  const digit = red ? '5' : String(rank);
  return (
    hcText(digit, 88, 84, colour) +
    hcText(suit.toUpperCase(), 122, 26, colour, 700) +
    (red ? bar(26, 96, 48, 5, RED) : '')
  );
}

// ---------------------------------------------------------------------------
// Assembly
// ---------------------------------------------------------------------------

/**
 * The markup for one face of an **inline** set.
 *
 * Returns `''` for a fetched set — its symbols are not generated here and are not this module's to
 * produce. Callers that need "is there a face for this" should ask {@link TILE_SET_INFO} what kind
 * of set they are holding.
 */
export function faceMarkup(tile: TileStr, set: TileSet): string {
  if (TILE_SET_INFO[set].source.kind !== 'inline') return '';
  return highContrastFace(tile);
}

/** DOM id of a face symbol. Namespaced: both sets can be in one document at once. */
export function faceSymbolId(tile: TileStr, set: TileSet): string {
  return `${TILE_SET_INFO[set].idPrefix}${tile}`;
}

/** DOM id of the face-down tile for a set, or `null` when it does not draw one. */
export function backSymbolId(set: TileSet): string | null {
  return TILE_SET_INFO[set].backSymbolId;
}

/**
 * The sprite for one inline set, as `<symbol>` elements.
 *
 * Inlined into the document rather than fetched, unlike the traditional sheet: this one is small,
 * and it is the fallback, so it has to be there before anything can go wrong.
 */
export function spriteMarkup(set: TileSet): string {
  if (TILE_SET_INFO[set].source.kind !== 'inline') return '';
  return ALL_TILE_STRS.map(
    (tile) =>
      `<symbol id="${faceSymbolId(tile, set)}" viewBox="${FACE_VIEWBOX}">${faceMarkup(tile, set)}</symbol>`,
  ).join('');
}
