import { Injectable, signal } from '@angular/core';

import { TILE_SETS, TILE_SET_INFO, spriteMarkup } from './tile-faces';
import type { TileSet } from './tile-faces';

const SPRITE_ID = 'mj-tile-sprite';

/**
 * Puts the tile symbols in the document.
 *
 * Two kinds of set, handled differently on purpose:
 *
 * - **Inline** (`high-contrast`) is generated by `tile-faces.ts` and injected synchronously, so it
 *   is available on the first paint and cannot fail.
 * - **Fetched** (`traditional`) is a 284 kB sprite sheet from `public/tiles/`, pulled in once and
 *   cached by the browser independently of the app bundle. `index.html` preloads it so the request
 *   overlaps the JS rather than following it.
 *
 * Written imperatively rather than as a component with `[innerHTML]` for one reason: Angular's HTML
 * sanitizer strips `<symbol>`, so a template would need `bypassSecurityTrustHtml`, and a
 * `bypassSecurityTrust*` call is a thing reviewers have to think about every time they see it.
 * Setting `innerHTML` on an `<svg>` element parses in the SVG namespace and needs no bypass. The
 * fetched sheet is same-origin, generated at build time from vendored files, and never touches
 * anything a server said.
 */
@Injectable({ providedIn: 'root' })
export class TileSpriteService {
  private readonly installed = new Set<TileSet>();
  private readonly pending = new Map<TileSet, Promise<boolean>>();

  private readonly _ready = signal<readonly TileSet[]>([]);
  private readonly _failed = signal<readonly TileSet[]>([]);

  /** Sets whose symbols are in the document and safe to reference. */
  readonly ready = this._ready.asReadonly();
  /** Sets whose sheet could not be fetched — the UI falls back rather than drawing blank slabs. */
  readonly failed = this._failed.asReadonly();

  /** Install the inline sets now and start fetching the rest. Safe to call repeatedly. */
  install(): void {
    for (const set of TILE_SETS) void this.ensure(set);
  }

  /**
   * Make one set available, returning whether it succeeded.
   *
   * Concurrent callers share a request: a board with 130 tiles on it must not become 130 fetches.
   */
  async ensure(set: TileSet): Promise<boolean> {
    if (this.installed.has(set)) return true;
    const inFlight = this.pending.get(set);
    if (inFlight !== undefined) return inFlight;

    const source = TILE_SET_INFO[set].source;
    if (source.kind === 'inline') {
      this.inject(set, spriteMarkup(set));
      return true;
    }

    const request = this.fetchSheet(set, source.url).finally(() => {
      this.pending.delete(set);
    });
    this.pending.set(set, request);
    return request;
  }

  private async fetchSheet(set: TileSet, url: string): Promise<boolean> {
    try {
      const response = await fetch(url, { cache: 'force-cache' });
      if (!response.ok) throw new Error(`HTTP ${String(response.status)}`);
      const markup = await response.text();
      // Take only the symbols; the sheet's own <svg> wrapper is not wanted in the document.
      const symbols = /<svg[^>]*>([\s\S]*)<\/svg>/.exec(markup)?.[1] ?? '';
      if (!symbols.includes('<symbol')) throw new Error('no symbols in the sheet');
      this.inject(set, symbols);
      return true;
    } catch {
      // A missing sheet is not a broken game: the inline set is already in the document, and the
      // tile component switches to it rather than rendering 136 empty slabs.
      this._failed.update((sets) => (sets.includes(set) ? sets : [...sets, set]));
      return false;
    }
  }

  private inject(set: TileSet, markup: string): void {
    if (markup.length === 0) return;
    const doc = globalThis.document as Document | undefined;
    if (doc === undefined) return;

    let host = doc.getElementById(SPRITE_ID) as SVGSVGElement | null;
    if (host === null) {
      host = doc.createElementNS('http://www.w3.org/2000/svg', 'svg');
      host.setAttribute('id', SPRITE_ID);
      host.setAttribute('aria-hidden', 'true');
      host.setAttribute('focusable', 'false');
      // Not `display: none`: a hidden ancestor makes `<use>` fail to resolve in some engines.
      host.setAttribute(
        'style',
        'position:absolute;width:0;height:0;overflow:hidden;pointer-events:none',
      );
      doc.body.append(host);
    }

    const group = doc.createElementNS('http://www.w3.org/2000/svg', 'g');
    group.setAttribute('data-set', set);
    group.innerHTML = markup;
    host.append(group);

    this.installed.add(set);
    this._ready.update((sets) => (sets.includes(set) ? sets : [...sets, set]));
  }
}
