/**
 * Actions, events and the shared game vocabulary.
 *
 * Spec: `docs/03-domain-model.md` §§3, 5, 6 and `docs/01-ruleset.md` §§10, 12, 13.
 *
 * **Wire form.** Everything in this file is the *wire* representation: tiles are `TileStr`.
 * The engine's internal action/event types use `TileId` and live in `src/engine/`; the gateway
 * converts between them (resolving a `TileStr` against the player's actual hand, which is why
 * the conversion is context-dependent and cannot live here).
 *
 * This module has ZERO dependencies beyond sibling contract modules.
 */

import type { TileKind, TileStr } from './tiles.js';

// ---------------------------------------------------------------------------
// Seats and winds
// ---------------------------------------------------------------------------

/** Absolute seat, fixed for the whole game. Seat 0 is the starting dealer. */
export type Seat = 0 | 1 | 2 | 3;

/** East, South, West, North. */
export type Wind = 0 | 1 | 2 | 3;

export const SEATS: readonly Seat[] = [0, 1, 2, 3];

export const WIND_EAST: Wind = 0;
export const WIND_SOUTH: Wind = 1;
export const WIND_WEST: Wind = 2;
export const WIND_NORTH: Wind = 3;

export function isSeat(value: unknown): value is Seat {
  return value === 0 || value === 1 || value === 2 || value === 3;
}

/** Seat wind for a hand: `(seat - dealer + 4) % 4`. Absolute seats only. */
export function seatWind(seat: Seat, dealerSeat: Seat): Wind {
  return ((seat - dealerSeat + 4) % 4) as Wind;
}

/** The seat `n` places counter-clockwise from `seat` (1 = shimocha / to your right in turn order). */
export function seatFrom(seat: Seat, offset: number): Seat {
  return ((((seat + offset) % 4) + 4) % 4) as Seat;
}

// ---------------------------------------------------------------------------
// Melds and discards
// ---------------------------------------------------------------------------

export type MeldType = 'chi' | 'pon' | 'daiminkan' | 'shouminkan' | 'ankan';

export const MELD_TYPES = [
  'chi',
  'pon',
  'daiminkan',
  'shouminkan',
  'ankan',
] as const satisfies readonly MeldType[];

/** A meld as it appears on the wire. Melds are always public. */
export interface MeldWire {
  type: MeldType;
  /** 3 tiles for chi/pon, 4 for any kan. */
  tiles: TileStr[];
  /** The tile taken from a discard; `null` for ankan. A shouminkan keeps its original pon call. */
  calledTile: TileStr | null;
  /** Whose discard it came from; `null` for ankan. */
  from: Seat | null;
  /** Index within `tiles` of the called tile — drives rotated-tile rendering. */
  calledIndex: number | null;
}

export interface DiscardWire {
  tile: TileStr;
  /** Discarded immediately after drawing. */
  tsumogiri: boolean;
  /** The riichi declaration discard — rendered rotated. */
  riichiDeclaration: boolean;
  /** Set when someone calls it. Matters for nagashi mangan. */
  calledBy: Seat | null;
}

// ---------------------------------------------------------------------------
// Actions
// ---------------------------------------------------------------------------

/** Server-initiated draw. Never sent by a client. */
export interface DrawAction {
  type: 'draw';
}

/**
 * Discard, optionally declaring riichi. Declaring riichi and choosing the discard is
 * one decision and one action — splitting it creates an invalid intermediate state.
 */
export interface DiscardAction {
  type: 'discard';
  tile: TileStr;
  riichi?: boolean;
}

/** Chi — the two tiles from your own hand. Left player's discard only. */
export interface ChiAction {
  type: 'chi';
  tiles: [TileStr, TileStr];
}

/** Pon — the two tiles from your own hand. */
export interface PonAction {
  type: 'pon';
  tiles: [TileStr, TileStr];
}

/** Open kan on a discard. */
export interface DaiminkanAction {
  type: 'daiminkan';
}

/** Added kan: the 4th tile onto your own pon. Robbable (chankan). */
export interface ShouminkanAction {
  type: 'shouminkan';
  tile: TileStr;
}

/** Concealed kan, from 4 in hand. Keeps the hand closed. */
export interface AnkanAction {
  type: 'ankan';
  kind: TileKind;
}

export interface TsumoAction {
  type: 'tsumo';
}

export interface RonAction {
  type: 'ron';
}

/** Nine-terminals abort, on your first draw with no call having occurred. */
export interface KyuushuAction {
  type: 'kyuushu';
}

/** Decline an open decision window. */
export interface PassAction {
  type: 'pass';
}

/** Timeout / bot-takeover tsumogiri. Generated by the table, never sent by a client. */
export interface AutoDiscardAction {
  type: 'auto-discard';
}

export type Action =
  | DrawAction
  | DiscardAction
  | ChiAction
  | PonAction
  | DaiminkanAction
  | ShouminkanAction
  | AnkanAction
  | TsumoAction
  | RonAction
  | KyuushuAction
  | PassAction
  | AutoDiscardAction;

export type ActionType = Action['type'];

/** Actions a client may originate. `draw` and `auto-discard` are server-side only. */
export type ClientAction = Exclude<Action, DrawAction | AutoDiscardAction>;

export const SERVER_ONLY_ACTION_TYPES: readonly ActionType[] = ['draw', 'auto-discard'];

/**
 * Call priority on a discard: `ron > pon = kan > chi`.
 * Higher wins. Ties between rons are resolved by `docs/01-ruleset.md` §9.
 */
export const CALL_PRIORITY: Readonly<Record<'ron' | 'pon' | 'daiminkan' | 'chi' | 'pass', number>> =
  {
    ron: 3,
    pon: 2,
    daiminkan: 2,
    chi: 1,
    pass: 0,
  };

// ---------------------------------------------------------------------------
// Rules
// ---------------------------------------------------------------------------

export type GameLength = 'tonpuusen' | 'hanchan';

export type RuleProfile = 'standard';

/** `docs/01-ruleset.md` §13. v1 ships `standard` only, but nothing may hardcode these values. */
export interface RuleConfig {
  profile: RuleProfile;
  length: GameLength;
  startingPoints: number;
  returnPoints: number;
  /** 1st/2nd/3rd/4th, in units of 1000. */
  uma: [number, number, number, number];
  redFives: { m: number; p: number; s: number };
  /** Open tanyao. */
  kuitan: boolean;
  /** Swap calling permitted. `false` = forbidden. */
  kuikae: boolean;
  atozuke: boolean;
  agariYame: boolean;
  /** Bust ends the game. */
  tobi: boolean;
  enchousen: boolean;
  nagashiMangan: boolean;
  /** Triple ron aborts instead. */
  doubleRon: boolean;
  sanchahouAborts: boolean;
  /** Pao + daiminkan rinshan liability. */
  sekininBarai: boolean;
  kazoeYakuman: boolean;
  doubleYakuman: boolean;
  renhou: 'none' | 'mangan' | 'yakuman';
  kiriageMangan: boolean;
  /** Kokushi may rob an ankan. */
  chankanOnAnkan: boolean;
  uraDora: boolean;
  kanDora: boolean;
  kanUraDora: boolean;
  ippatsu: boolean;
}

/** The v1 profile. Table creation may only vary `length`. */
export const STANDARD_RULES: RuleConfig = {
  profile: 'standard',
  length: 'hanchan',
  startingPoints: 25_000,
  returnPoints: 30_000,
  uma: [15, 5, -5, -15],
  redFives: { m: 1, p: 1, s: 1 },
  kuitan: true,
  kuikae: false,
  atozuke: true,
  agariYame: true,
  tobi: true,
  enchousen: true,
  nagashiMangan: true,
  doubleRon: true,
  sanchahouAborts: true,
  sekininBarai: true,
  kazoeYakuman: true,
  doubleYakuman: false,
  renhou: 'none',
  kiriageMangan: false,
  chankanOnAnkan: false,
  uraDora: true,
  kanDora: true,
  kanUraDora: true,
  ippatsu: true,
};

// ---------------------------------------------------------------------------
// Yaku
// ---------------------------------------------------------------------------

/**
 * Stable yaku identifiers — used in the event log, the database, and as client i18n keys.
 * Never renumber or rename: historical games reference these strings.
 * Values: `docs/01-ruleset.md` §10.
 */
export const YAKU_IDS = [
  // 1 han
  'riichi',
  'ippatsu',
  'menzen_tsumo',
  'pinfu',
  'tanyao',
  'yakuhai_haku',
  'yakuhai_hatsu',
  'yakuhai_chun',
  'yakuhai_seat_wind',
  'yakuhai_round_wind',
  'iipeikou',
  'haitei_raoyue',
  'houtei_raoyui',
  'rinshan_kaihou',
  'chankan',
  // 2 han
  'double_riichi',
  'chiitoitsu',
  'sanshoku_doujun',
  'ittsuu',
  'chanta',
  'toitoi',
  'sanankou',
  'sanshoku_doukou',
  'sankantsu',
  'shousangen',
  'honroutou',
  // 2–3 han
  'honitsu',
  // 3 han
  'junchan',
  'ryanpeikou',
  // 6 han
  'chinitsu',
  // yakuman
  'kokushi_musou',
  'suuankou',
  'daisangen',
  'shousuushii',
  'daisuushii',
  'tsuuiisou',
  'chinroutou',
  'ryuuiisou',
  'chuuren_poutou',
  'suukantsu',
  'tenhou',
  'chiihou',
] as const;

export type YakuId = (typeof YAKU_IDS)[number];

/**
 * The yakuman of `docs/01-ruleset.md` §10. Twelve, not thirteen: renhou is disabled
 * (`renhou: 'none'`) and double yakuman are off, so kokushi-13-wait and suuankou-tanki
 * are not separate ids.
 */
export const YAKUMAN_IDS = [
  'kokushi_musou',
  'suuankou',
  'daisangen',
  'shousuushii',
  'daisuushii',
  'tsuuiisou',
  'chinroutou',
  'ryuuiisou',
  'chuuren_poutou',
  'suukantsu',
  'tenhou',
  'chiihou',
] as const satisfies readonly YakuId[];

export type YakumanId = (typeof YAKUMAN_IDS)[number];

export interface YakuValue {
  name: YakuId;
  han: number;
}

/** Named limits. `kazoe_yakuman` is 13+ han from ordinary yaku; it never stacks with a true yakuman. */
export type LimitName = 'mangan' | 'haneman' | 'baiman' | 'sanbaiman' | 'kazoe_yakuman' | 'yakuman';

// ---------------------------------------------------------------------------
// Results
// ---------------------------------------------------------------------------

export interface AgariResult {
  seat: Seat;
  /** The discarder; `=== seat` for tsumo. */
  from: Seat;
  hand: TileStr[];
  melds: MeldWire[];
  winningTile: TileStr;
  yaku: YakuValue[];
  yakuman: YakuId[];
  dora: number;
  uraDora: number;
  redDora: number;
  han: number;
  fu: number;
  /** Total gained, including honba and riichi sticks. */
  points: number;
  /** Per-seat; sums to 0 across all winners of the hand. */
  scoreDeltas: number[];
  limitName: LimitName | null;
}

/**
 * `exhaustive` plus the five abortive draws of `docs/01-ruleset.md` §8.
 * Nagashi mangan is an *exhaustive* draw with a different payment, reported via
 * `RyuukyokuEvent.nagashi`.
 */
export type RyuukyokuReason =
  'exhaustive' | 'kyuushu_kyuuhai' | 'suufon_renda' | 'suucha_riichi' | 'suukaikan' | 'sanchahou';

export interface Placement {
  seat: Seat;
  /** 1…4. Ties broken by seat order from the starting dealer; no split placements. */
  place: 1 | 2 | 3 | 4;
  finalScore: number;
  /** After uma + oka, in units of 1000. */
  netScore: number;
}

export type BotLevel = 'easy' | 'normal' | 'hard';

export interface PlayerInfo {
  /** `null` for a pure bot seat. */
  userId: string | null;
  displayName: string;
  avatarId: string;
  isBot: boolean;
  botLevel: BotLevel | null;
}

// ---------------------------------------------------------------------------
// Events
// ---------------------------------------------------------------------------

/**
 * The engine's output and the only thing persisted or sent to clients: state is `fold(events)`.
 * Every event is projected per recipient before it leaves the server — see `projectFor()`
 * and the redaction table in `docs/03-domain-model.md` §6.
 */
export interface GameStartEvent {
  t: 'game-start';
  config: RuleConfig;
  players: PlayerInfo[];
  /** sha256 of the seed, published at game start so the wall can be verified afterwards. */
  seedHash: string;
  /** Withheld from clients until `game-end`. */
  seed?: string;
}

export interface HandStartEvent {
  t: 'hand-start';
  handIndex: number;
  round: Wind;
  kyoku: number;
  honba: number;
  riichiSticks: number;
  dealer: Seat;
  scores: number[];
  /** Index === seat. The real 13 tiles for the viewer, `null` for everyone else. */
  hands: (TileStr[] | null)[];
  doraIndicator: TileStr;
}

export interface DrawEvent {
  t: 'draw';
  seat: Seat;
  /** Present only for the drawer. */
  tile: TileStr | null;
  fromRinshan: boolean;
  wallRemaining: number;
}

export interface DiscardEvent {
  t: 'discard';
  seat: Seat;
  tile: TileStr;
  tsumogiri: boolean;
  riichi: boolean;
}

export interface CallEvent {
  t: 'call';
  seat: Seat;
  meld: MeldWire;
  from: Seat;
}

export interface RiichiAcceptedEvent {
  t: 'riichi-accepted';
  seat: Seat;
  /** Sticks on the table after the deposit. */
  sticks: number;
  scores: number[];
}

export interface DoraRevealedEvent {
  t: 'dora-revealed';
  indicator: TileStr;
}

export interface AgariEvent {
  t: 'agari';
  winners: AgariResult[];
  scores: number[];
  scoreDeltas: number[];
  /** Revealed only when a riichi hand won. */
  uraIndicators?: TileStr[];
}

export interface RyuukyokuEvent {
  t: 'ryuukyoku';
  reason: RyuukyokuReason;
  /** Index === seat; meaningful for `exhaustive` only. */
  tenpai: boolean[];
  /** Revealed hands at an exhaustive draw; `null` where not revealed. */
  hands: (TileStr[] | null)[];
  scores: number[];
  scoreDeltas: number[];
  /** Seats scoring nagashi mangan, if any. */
  nagashi?: Seat[];
}

export interface HandEndEvent {
  t: 'hand-end';
  nextDealer: Seat;
  nextHonba: number;
  /** Sticks carried over to the next hand. */
  riichiSticks: number;
}

export interface GameEndEvent {
  t: 'game-end';
  placements: Placement[];
  /** Released here so any client can re-derive the walls and verify them against `seedHash`. */
  seed: string;
}

export type GameEvent =
  | GameStartEvent
  | HandStartEvent
  | DrawEvent
  | DiscardEvent
  | CallEvent
  | RiichiAcceptedEvent
  | DoraRevealedEvent
  | AgariEvent
  | RyuukyokuEvent
  | HandEndEvent
  | GameEndEvent;

export type GameEventType = GameEvent['t'];
